### ISSUE TITLE
How to verify the camera position and angle.

### ISSUE THREAD

**Issue by KurokoWD** [chengxuxin/extreme-parkour#9]
Thanks to your wonderful work.
I noticed that you set the position and angle in 'legged_robot_config.py' and I wonder how you verified the position and angle of the camera. Because I am trying to train a policy on aliengo by following your method, but I can't find any information about camera in unitree's urdf.
Can you help me?
Looking forward your reply.

**Comment by chengxuxin** [comment]
You can add a visualization in urdf. Take a look at this example [here:](https://github.com/chengxuxin/extreme-parkour/blob/4ea4d0f88b43dcdc6926254906826592345fc39f/legged_gym/resources/robots/a1/urdf/a1.urdf#L55)

You can try to adjust the camera box until it is close to the actual camera position, since the exact camera position is not available from unitree.

**Comment by KurokoWD** [comment]
Thanks to your reply, I will try.

**Comment by AlfredFang** [comment]
@KurokoWD 
May I ask if you can share some information about Aliengo's configuration? I am unable to converge after training on aliengo

**Comment by KurokoWD** [comment]
@AlfredFang
I have calibrated the camera's intrinsic and extrinsic parameters on real robot.

**Comment by AlfredFang** [comment]
@KurokoWD Could you please take a look at your aliengo_config.py and legged_robot_config.py files? My current reward after 15k iterations of training in the first phase is only about 2

**Comment by wyy419** [comment]
> @AlfredFang I have calibrated the camera's intrinsic and extrinsic parameters on real robot.

Excuse me, but have you successfully completed the deployment?
